### ISSUE TITLE
The expected object props of `alreadyMarked` is not consistent

### ISSUE THREAD

**Issue by dremonkey** [Skycatch/model-trainer-image-marker#3]
According to the documentation `alreadyMarked` should look like
```
[{
  'cpId': 'PoI-1',
  'x': 2500,
  'y': 1000
}]
```

which is consistent with the structure that the `currentMark` is expecting.

However according to the code the actual schema that `alreadyMarked` is expecting is
```
[{
  xPos: <int>,
  yPos: <int>, 
  cpId: <int>
}]
```
(see https://github.com/Skycatch/model-trainer-image-marker/blob/master/src/lib/index.js#L438) which is oddly inconsistent in my opinion should be changed to match the docs and currentMark structure so that there is a consistent schema for what a `mark` object should look like.

Thoughts?

**Comment by bneigher** [comment]
thanks for the feedback -- just took your suggestion and updated the event payload respectively 49a76c0
